ALTER TABLE expenses
  ADD COLUMN active TINYINT(1) NOT NULL DEFAULT 1 AFTER occurred_on,
  ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

