<article class="cartao" id="sessoes-conta">
    <div class="cabecalho-cartao"><div><span class="sobretitulo">SESSÕES E DISPOSITIVOS</span><h2>Acessos da sua conta</h2><p class="suave">Os endereços e identificadores técnicos são armazenados somente como hash.</p></div><span class="etiqueta verde"><?= count($accountSessions) ?> ATIVA(S)</span></div>
    <form class="formulario alerta-novo-dispositivo" method="post" action="/admin/account/security-alerts"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><label class="opcao opcao-destaque"><input type="checkbox" name="new_device_alerts_enabled" <?= !empty($user['new_device_alerts_enabled'])?'checked':'' ?>><span><b>Avisar sobre novo dispositivo</b><small>Envia um alerta ao e-mail confirmado quando um navegador ainda não reconhecido acessa sua conta.</small></span></label><button class="botao pequeno" type="submit">Salvar preferência</button></form>
    <div class="lista-sessoes-conta">
        <?php foreach($accountSessions as$accountSession):$isCurrent=(int)$accountSession['id']===(int)($_SESSION['auth_session_id']??0);?>
            <article><div><b><?= e($accountSession['device_label']) ?></b><small><?= $isCurrent?'Sessão atual · ':'' ?>Última atividade em <?= e((new DateTimeImmutable($accountSession['last_seen_at']))->format('d/m/Y H:i')) ?></small><small>Iniciada em <?= e((new DateTimeImmutable($accountSession['created_at']))->format('d/m/Y H:i')) ?> · expira <?= e((new DateTimeImmutable($accountSession['expires_at']))->format('d/m/Y H:i')) ?></small></div><?php if($isCurrent):?><span class="etiqueta verde">ESTE DISPOSITIVO</span><?php else:?><form method="post" action="/admin/account/session/revoke"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$accountSession['id'] ?>"><button class="botao pequeno perigo" type="submit">Encerrar acesso</button></form><?php endif;?></article>
        <?php endforeach;?>
    </div>
    <?php if(count($accountSessions)>1):?><form method="post" action="/admin/account/session/revoke-others"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><button class="botao perigo" type="submit">Encerrar todos os outros acessos</button></form><?php endif;?>
</article>
