<?php
$trialEnds = $store['trial_ends_at'] ? new DateTimeImmutable($store['trial_ends_at']) : null;
$today = new DateTimeImmutable('today');
$trialDays = $trialEnds && $trialEnds >= $today ? (int) $today->diff($trialEnds)->format('%a') : 0;
$billingStatusLabels=['pending'=>'Aguardando pagamento','trialing'=>'Em teste','active'=>'Ativa','past_due'=>'Pagamento pendente','cancelled'=>'Cancelada','expired'=>'Expirada'];
$publicKey=mercadopago_public_key();
$gatewayReady=mercadopago_configured()&&$publicKey!==null&&mercadopago_plan_id('monthly')!==null&&mercadopago_plan_id('annual')!==null;
$subscriptionActive=$billingAccount&&($billingAccount['status']==='active'||($billingAccount['status']==='trialing'&&!empty($billingAccount['provider_subscription_ref'])));
$checkoutAllowed=$gatewayReady&&!$subscriptionActive&&(mercadopago_environment()==='sandbox'||$trialDays===0);
$benefits = [
    ['∞', 'Produtos e pedidos ilimitados'],
    ['✓', 'Vitrine personalizada com seu link'],
    ['◉', 'Pedidos organizados no painel'],
    ['⌖', 'Entrega, retirada e taxas por bairro'],
    ['▦', 'QR Code para cardápio e mesas'],
    ['⚡', 'PDV, Garçom e Cozinha integrados'],
    ['▥', 'Relatórios de vendas e financeiro'],
    ['♧', 'Acessos para toda a sua equipe'],
];
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Assinatura e pagamento · MJDev Digital</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700;800&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><script src="/assets/admin-theme.js?v=20260826-tema1"></script><link rel="stylesheet" href="/assets/admin.css?v=20260903-review1"><?php if($gatewayReady):?><link rel="stylesheet" href="/assets/billing-payment.css?v=20260901-token2"><script src="https://sdk.mercadopago.com/js/v2"></script><script src="/assets/billing-payment.js?v=20260901-token2" defer></script><?php endif;?></head><body><div class="aplicativo"><aside class="barra-lateral" id="sidebar"><div class="marca"><span class="simbolo-marca">MJ</span><div><strong>MJDev Digital</strong><small>PAINEL DE GESTÃO</small></div><button class="icone movel" id="closeMenu" type="button" aria-label="Fechar menu">×</button></div><nav><?= admin_navigation($user['role'], 'billing') ?></nav><?= admin_store_card($store) ?><form class="sair-painel" method="post" action="/sair"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><button class="botao perigo">Sair do painel</button></form></aside><div class="fundo-sobreposto fundo-menu" id="menuBackdrop"></div><main class="estrutura"><header class="barra-superior"><button class="icone movel" id="openMenu" type="button" aria-label="Abrir menu">☰</button><div class="cabecalho-pagina"><span><?= e(strtoupper($store['name'])) ?></span><h1>Assinatura e pagamento</h1></div><?= admin_header_actions($orders, $user) ?></header><section class="conteudo"><?php if ($flash): ?><div class="aviso <?= e($flash[0]) ?>"><?= e($flash[1]) ?></div><?php endif; ?>
<article class="cartao faixa-lancamento"><div><span class="sobretitulo">OFERTA FUNDADORES · TEMPO LIMITADO</span><h2>Venda mais pagando menos desde o primeiro pedido.</h2><p>Condição de lançamento para colocar toda a operação no digital.</p></div><div class="economia-lancamento"><small>ECONOMIZE ATÉ</small><strong>40%</strong><span>no primeiro ano</span></div></article>
<div class="titulo-cobranca"><div><span class="sobretitulo">PLANOS COMPLETOS</span><h2>Escolha como quer começar</h2></div><span class="cobranca-segura">● <?= $trialDays > 0 ? $trialDays . ' dias restantes no teste' : '14 dias grátis após publicar' ?></span></div>
<?php if($billingAccount):?><div class="aviso informativo"><b>Assinatura: <?= e($billingStatusLabels[$billingAccount['status']]??'Em análise') ?></b><br>O retorno do pagamento não ativa a conta sozinho. A confirmação será feita pelo webhook autenticado do Mercado Pago.<?php if(!empty($billingAccount['provider_subscription_ref'])&&in_array($billingAccount['status'],['pending','trialing','past_due'],true)):?><form method="post" action="/admin/billing/reconcile" style="margin-top:10px"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><button class="botao" type="submit">Consultar situação no Mercado Pago</button></form><?php endif;?><?php if(!empty($billingAccount['provider_subscription_ref'])&&in_array($billingAccount['status'],['active','past_due'],true)):?><details class="gerenciar-assinatura"><summary>Gerenciar assinatura</summary><form method="post" action="/admin/billing/cancel"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><label class="opcao"><input type="checkbox" name="confirm_cancel" value="1" required><span><b>Confirmo o cancelamento</b><small>A cobrança recorrente será encerrada no Mercado Pago. Esta ação não estorna cobranças anteriores.</small></span></label><button class="botao perigo" type="submit">Cancelar assinatura</button></form></details><?php endif;?></div><?php endif;?>
<div class="grade-precos"><article class="cartao-preco"><div class="topo-preco"><span class="icone-plano">30</span><div><small>FLEXIBILIDADE TOTAL</small><h2>Mensal</h2></div></div><div class="preco-antigo">De <s>R$ 99,00</s> por</div><div class="preco-lancamento"><sup>R$</sup><strong>59</strong><span>,90<br><small>/mês</small></span></div><p class="condicao-preco">Valor de lançamento nos primeiros 3 meses.</p><ul class="lista-beneficios"><?php foreach ($benefits as $benefit): ?><li><span><?= e($benefit[0]) ?></span><div><b><?= e($benefit[1]) ?></b><small>Incluso sem custo adicional</small></div></li><?php endforeach; ?></ul><button class="botao chamada-preco" type="button" data-billing-plan="monthly" data-billing-amount="59.90" <?= !$checkoutAllowed?'disabled':'' ?>><?= $subscriptionActive?'Assinatura ativa':(!$gatewayReady?'Pagamento online indisponível':(!$checkoutAllowed?'Disponível ao final do teste':'Assinar plano mensal')) ?></button><small class="letras-miudas">Depois, R$ 99,00/mês. Sem fidelidade.</small></article>
<article class="cartao-preco plano-destacado"><div class="faixa-popular">MAIS ESCOLHIDO</div><div class="topo-preco"><span class="icone-plano">365</span><div><small>MELHOR CUSTO-BENEFÍCIO</small><h2>Anual</h2></div><span class="etiqueta amarelo">Economize R$ 400</span></div><div class="preco-antigo">De <s>R$ 999,00</s> por</div><div class="preco-lancamento"><sup>R$</sup><strong>599</strong><span>,00<br><small>/ano</small></span></div><p class="condicao-preco"><b>Equivale a R$ 49,92/mês.</b> Condição de lançamento.</p><ul class="lista-beneficios"><?php foreach ($benefits as $benefit): ?><li><span><?= e($benefit[0]) ?></span><div><b><?= e($benefit[1]) ?></b><small>Incluso sem custo adicional</small></div></li><?php endforeach; ?></ul><button class="botao primario chamada-preco" type="button" data-billing-plan="annual" data-billing-amount="599.00" <?= !$checkoutAllowed?'disabled':'' ?>><?= $subscriptionActive?'Assinatura ativa':(!$gatewayReady?'Pagamento online indisponível':(!$checkoutAllowed?'Disponível ao final do teste':'Assinar plano anual')) ?></button><small class="letras-miudas">Pagamento anual. Renovação informada com antecedência.</small></article></div>
<article class="cartao rodape-cobranca"><div><b>Todos os recursos. Nenhuma taxa por pedido.</b><small>Seu faturamento continua sendo seu.</small></div><div><b><?= mercadopago_environment()==='sandbox'?'Ambiente de homologação':'Pagamento seguro pelo Mercado Pago' ?></b><small><?= mercadopago_environment()==='sandbox'?'Nenhuma cobrança real deve ser realizada neste ambiente.':'A confirmação financeira ocorre exclusivamente no servidor.' ?></small></div></article>
<?php if($gatewayReady):?><dialog class="modal-pagamento" id="billingPaymentDialog"><div class="cabecalho-modal-pagamento"><div><span class="sobretitulo">CHECKOUT PROTEGIDO</span><h2 id="billingPaymentTitle">Assinar plano</h2><p id="billingPaymentPlanSummary">Plano mensal · R$ 59,90 por mês</p></div><button class="fechar-pagamento" type="button" data-close-billing aria-label="Fechar pagamento">×</button></div><div class="selo-provedor"><span class="icone-seguranca" aria-hidden="true">✓</span><div><b>Pagamento processado pelo Mercado Pago</b><small>Número do cartão e código de segurança não são armazenados pela MJDev.</small></div></div><form id="billingCardForm" class="formulario formulario-pagamento" method="post" action="/admin/billing/checkout" data-public-key="<?= e((string)$publicKey) ?>"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="plan" id="billingPlan" value="monthly"><input type="hidden" name="card_token" id="billingCardToken"><input type="hidden" id="billingAmount" value="59.90"><div class="grade duas-colunas grade-cartao"><label class="campo campo-numero-cartao"><span>Número do cartão</span><div class="campo-seguro" id="form-checkout__cardNumber"></div></label><label class="campo"><span>Validade</span><div class="campo-seguro" id="form-checkout__expirationDate"></div></label><label class="campo"><span>Código de segurança</span><div class="campo-seguro" id="form-checkout__securityCode"></div></label><label class="campo campo-nome-cartao"><span>Nome impresso no cartão</span><input id="form-checkout__cardholderName" autocomplete="cc-name" placeholder="Como aparece no cartão" required></label><label class="campo"><span>CPF ou CNPJ</span><div class="grade documento-pagamento"><select id="form-checkout__identificationType" aria-label="Tipo de documento"></select><input id="form-checkout__identificationNumber" name="identification_number" inputmode="numeric" autocomplete="off" placeholder="Somente números" required></div></label><label class="campo"><span>E-mail para cobrança</span><input id="form-checkout__cardholderEmail" name="payer_email" type="email" autocomplete="email" maxlength="190" placeholder="seuemail@exemplo.com" required></label><select id="form-checkout__issuer" hidden></select><select id="form-checkout__installments" hidden></select></div><div class="aviso error" id="billingPaymentError" role="alert" hidden>Não foi possível validar o cartão. Revise os dados e tente novamente.</div><button class="botao primario completo botao-confirmar-pagamento" id="billingPaymentSubmit" type="submit"><span aria-hidden="true">✓</span> Autorizar assinatura com segurança</button><div class="rodape-seguranca-pagamento"><span>Conexão protegida</span><span>Token de uso único</span><span>Confirmação por webhook</span></div></form></dialog><?php endif;?>
</section></main></div><script src="/assets/admin-ui.js?v=20260903-review1" defer></script></body></html>

