<?php
$money=fn(int $value): string=>'R$ '.number_format($value/100,2,',','.');
$titles=['stock'=>'Visão geral do estoque','moves'=>'Movimentações','customers'=>'Clientes'];
$title=$titles[$section]??'Gestão';
$tracked=array_values(array_filter($products,fn($product)=>$product['stock_quantity']!==null));
$lowStock=array_values(array_filter($tracked,fn($product)=>(int)$product['stock_quantity']<=5));
$stockUnits=array_sum(array_map(fn($product)=>(int)$product['stock_quantity'],$tracked));
$stockValue=array_sum(array_map(fn($product)=>(int)$product['stock_quantity']*(int)$product['price_cents'],$tracked));
$customerOrders=array_sum(array_map(fn($customer)=>(int)$customer['order_count'],$customers));
$customerRevenue=array_sum(array_map(fn($customer)=>(int)$customer['lifetime_value_cents'],$customers));
$averageCustomer=$customers?(int)round($customerRevenue/count($customers)):0;
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($title) ?> · MJDev Digital</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700;800&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><script src="/assets/admin-theme.js?v=20260826-tema1"></script><link rel="stylesheet" href="/assets/admin.css?v=20260903-review1"></head><body class="secao-<?= e($section) ?>"><div class="aplicativo"><aside class="barra-lateral" id="sidebar" aria-label="Navegação principal"><div class="marca"><span class="simbolo-marca">MJ</span><div><strong>MJDev Digital</strong><small>PAINEL DE GESTÃO</small></div><button class="icone movel" id="closeMenu" type="button" aria-label="Fechar menu">×</button></div><nav><?= admin_navigation($user['role'],$section) ?></nav><?= admin_store_card($store) ?><form class="sair-painel" method="post" action="/sair"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><button class="botao perigo">Sair do painel</button></form></aside><div class="fundo-sobreposto fundo-menu" id="menuBackdrop"></div><main class="estrutura"><header class="barra-superior"><button class="icone movel" id="openMenu" type="button" aria-label="Abrir menu">☰</button><div class="cabecalho-pagina"><span><?= e(strtoupper($store['name'])) ?></span><h1><?= e($title) ?></h1></div><?= admin_header_actions($orders,$user) ?></header><section class="conteudo"><?php if($flash):?><div class="aviso <?= e($flash[0]) ?>"><?= e($flash[1]) ?></div><?php endif;?>

<?php if(in_array($section,['stock','moves'],true)):?>
<div class="introducao-modulo"><div><span class="sobretitulo"><?= $section==='moves'?'MOVIMENTAÇÕES › LISTAR':'VISÃO GERAL DO ESTOQUE › LISTAR' ?></span><h2><?= e($title) ?></h2><p>Gerencie <?= $section==='moves'?'movimentações':'o estoque' ?> com visão clara e ações rápidas.</p></div><?php if($products):?><button class="botao primario" type="button" data-open-stock>+ Ajuste de estoque</button><?php endif;?></div>
<div class="grade quatro-colunas metricas metricas-modulo"><article class="metrica"><small>Produtos controlados</small><strong><?= count($tracked) ?></strong><span>Itens com controle de saldo</span></article><article class="metrica"><small>Unidades em estoque</small><strong><?= $stockUnits ?></strong><span>Saldo total cadastrado</span></article><article class="metrica"><small>Estoque baixo</small><strong><?= count($lowStock) ?></strong><span>Produtos com até 5 unidades</span></article><article class="metrica"><small>Valor estimado</small><strong><?= $money($stockValue) ?></strong><span>Preço atual × quantidade</span></article></div>
<?php if($products):?><dialog class="modal-administrativo" id="stockDialog"><div class="cabecalho-modal"><div><span class="sobretitulo">NOVA MOVIMENTAÇÃO</span><h2>Ajustar estoque</h2></div><button class="icone" type="button" data-close-stock aria-label="Fechar">×</button></div><p class="suave">A alteração será persistida no histórico da empresa.</p><form class="formulario grade-formulario" method="post" action="/admin/stock/adjust"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><label>Produto<select name="product_id" required><?php foreach($products as$product):?><option value="<?= (int)$product['id'] ?>"><?= e($product['name']) ?> · <?= $product['stock_quantity']===null?'sem controle':(int)$product['stock_quantity'].' un.' ?></option><?php endforeach;?></select></label><label>Tipo<select name="movement_type"><option value="entry">Entrada</option><option value="exit">Saída</option><option value="adjustment">Ajuste de saldo</option></select></label><label>Quantidade<input type="number" name="quantity" required></label><label>Referência<input name="reference" maxlength="120" placeholder="Ex.: compra #129"></label><label class="completo">Observação<textarea name="notes" maxlength="500" rows="3" placeholder="Motivo da movimentação"></textarea></label><button class="botao primario completo">Registrar movimentação</button></form></dialog><?php endif;?>
<div class="barra-ferramentas"><label class="busca"><span>⌕</span><input class="busca-local" type="search" placeholder="Pesquisar" aria-label="Pesquisar <?= $section==='moves'?'movimentações':'produtos em estoque' ?>"></label><button class="botao" type="button" data-table-filter>☷ Filtros</button><?php if($products):?><button class="botao primario" type="button" data-open-stock>+ Ajuste de estoque</button><?php endif;?></div>
<article class="cartao cartao-tabela-administrativa"><div class="envoltorio-tabela"><table><thead><tr><?php if($section==='moves'):?><th>Data</th><th>Produto</th><th>Tipo</th><th>Quantidade</th><th>Saldo após</th><th>Referência</th><th>Observação</th><?php else:?><th>Produto</th><th>Categoria</th><th>Estoque</th><th>Mínimo</th><th>Valor estimado</th><th>Status</th><th>Ações</th><?php endif;?></tr></thead><tbody>
<?php if($section==='moves'):?><?php if(!$movements):?><tr><td colspan="7"><div class="estado-vazio compacto"><b>Sem movimentações</b><p>O histórico aparecerá após o primeiro ajuste.</p></div></td></tr><?php else:foreach($movements as$movement):?><tr><td><?= e(date('d/m/Y H:i',strtotime($movement['created_at']))) ?></td><td><b><?= e($movement['product_name']) ?></b></td><td><span class="etiqueta <?= $movement['movement_type']==='entry'?'verde':($movement['movement_type']==='exit'?'vermelho':'amarelo') ?>"><?= e(['entry'=>'Entrada','exit'=>'Saída','adjustment'=>'Ajuste'][$movement['movement_type']]??$movement['movement_type']) ?></span></td><td><?= (int)$movement['quantity'] ?></td><td><b><?= (int)$movement['balance_after'] ?></b></td><td><?= e($movement['reference']??'—') ?></td><td><?= e($movement['notes']??'—') ?></td></tr><?php endforeach;endif;?>
<?php else:?><?php if(!$products):?><tr><td colspan="7"><div class="estado-vazio compacto"><b>Estoque vazio</b><p>Cadastre produtos para iniciar o controle.</p></div></td></tr><?php else:foreach($products as$product):$quantity=$product['stock_quantity'];$isLow=$quantity!==null&&(int)$quantity<=5;?><tr><td><b><?= e($product['name']) ?></b><small><?= $product['active']?'Produto ativo':'Produto inativo' ?></small></td><td><?= e($product['category_name']) ?></td><td><?= $quantity===null?'Ilimitado':(int)$quantity.' un.' ?></td><td>5 un.</td><td><?= $quantity===null?'—':$money((int)$quantity*(int)$product['price_cents']) ?></td><td><span class="etiqueta <?= $quantity===null||!$isLow?'verde':((int)$quantity===0?'vermelho':'amarelo') ?>"><?= $quantity===null?'Sem controle':((int)$quantity===0?'Esgotado':($isLow?'Baixo':'OK')) ?></span></td><td><a class="botao pequeno" href="/admin?section=products">Editar</a></td></tr><?php endforeach;endif;?><?php endif;?></tbody></table></div><footer class="rodape-tabela"><span>Exibindo <?= $section==='moves'?count($movements):count($products) ?> resultado(s)</span><span>Dados reais da loja</span></footer></article>

<?php elseif($section==='customers'):?>
<div class="introducao-modulo"><div><span class="sobretitulo">CLIENTES › LISTAR</span><h2>Clientes</h2><p>Gerencie sua base de clientes com dados reais dos pedidos.</p></div><span class="contador-modulo"><?= count($customers) ?> cliente(s)</span></div>
<div class="grade quatro-colunas metricas metricas-modulo"><article class="metrica"><small>Clientes</small><strong><?= count($customers) ?></strong><span>Cadastros vinculados à loja</span></article><article class="metrica"><small>Pedidos realizados</small><strong><?= $customerOrders ?></strong><span>Total acumulado da base</span></article><article class="metrica"><small>Receita acumulada</small><strong><?= $money($customerRevenue) ?></strong><span>Somente pedidos válidos</span></article><article class="metrica"><small>Valor médio</small><strong><?= $money($averageCustomer) ?></strong><span>Receita por cliente</span></article></div>
<div class="barra-ferramentas"><label class="busca"><span>⌕</span><input class="busca-local" type="search" placeholder="Pesquisar" aria-label="Pesquisar clientes"></label><span class="resumo-ferramentas"><?= $customerOrders ?> pedidos · <?= $money($customerRevenue) ?> em compras</span></div>
<article class="cartao cartao-tabela-administrativa"><div class="envoltorio-tabela"><table><thead><tr><th>Cliente</th><th>Telefone</th><th>E-mail</th><th>Pedidos</th><th>Total comprado</th><th>Ticket médio</th></tr></thead><tbody><?php if(!$customers):?><tr><td colspan="6"><div class="estado-vazio compacto"><b>Nenhum cliente ainda</b><p>Os clientes aparecerão automaticamente após pedidos válidos.</p></div></td></tr><?php else:foreach($customers as$customer):?><tr><td><b><?= e($customer['name']) ?></b></td><td><?= e($customer['phone']) ?></td><td><?= e($customer['email']?:'—') ?></td><td><span class="etiqueta"><?= (int)$customer['order_count'] ?></span></td><td><b><?= $money((int)$customer['lifetime_value_cents']) ?></b></td><td><?= $money((int)$customer['order_count']>0?(int)round((int)$customer['lifetime_value_cents']/(int)$customer['order_count']):0) ?></td></tr><?php endforeach;endif;?></tbody></table></div><footer class="rodape-tabela"><span>Exibindo <?= count($customers) ?> resultado(s)</span><span>Valor médio <?= $money($averageCustomer) ?></span></footer></article>
<?php endif;?>
</section></main></div><script src="/assets/admin-ui.js?v=20260903-review1" defer></script></body></html>

