<?php
$money=fn(int $v)=>'R$ '.number_format($v/100,2,',','.');
$titles=['kitchen'=>'COZINHA · KDS','waiter'=>'GARÇOM','courier'=>'ENTREGADOR'];
$subtitles=['kitchen'=>'Fila de preparo em tempo real — toque para avançar.','waiter'=>'Atendimento rápido para salão e comandas.','courier'=>'Rotas, entregas e confirmações em tempo real.'];
$groupsById=array_column($optionGroups,null,'id');
$visibleOrders=array_filter($orders,fn($o)=>match($section){'kitchen'=>in_array($o['status'],['confirmed','preparing','ready'],true),'waiter'=>in_array($o['status'],['received','confirmed','preparing','ready'],true)&&$o['order_type']==='dine_in','courier'=>in_array($o['status'],['ready','out_for_delivery'],true)&&$o['order_type']==='delivery'});
$next=fn(string$status)=>match($section){'kitchen'=>['confirmed'=>'preparing','preparing'=>'ready'][$status]??null,'waiter'=>['received'=>'confirmed'][$status]??null,'courier'=>['ready'=>'out_for_delivery','out_for_delivery'=>'delivered'][$status]??null};
$buttonLabels=['confirmed'=>'Confirmar pedido','preparing'=>'Iniciar preparo','ready'=>'Marcar como pronto','out_for_delivery'=>'Iniciar entrega','delivered'=>'Confirmar entrega'];
$statusLabels=['received'=>'Recebido','confirmed'=>'Confirmado','preparing'=>'Em preparo','ready'=>'Pronto','out_for_delivery'=>'Saiu para entrega','delivered'=>'Entregue'];
$returnPath=['kitchen'=>'/cozinha','waiter'=>'/garcom','courier'=>'/entregador'][$section];
$activeTables=array_values(array_filter($tables,fn($t)=>$t['active']&&$t['status']!=='inactive'&&!empty($t['access_token_encrypted'])));
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($titles[$section]) ?> · MJDev Digital</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700;800&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><script src="/assets/admin-theme.js?v=20260826-tema1"></script><link rel="stylesheet" href="/assets/admin.css?v=20260903-review1"></head>
<body class="pagina-operacional"><header class="cabecalho-operacional"><a class="marca-operacional" href="/admin"><span class="simbolo-marca">MJ</span><span><small>ACESSO OPERACIONAL INDEPENDENTE</small><strong><?= e($titles[$section]) ?></strong></span></a><div class="acoes-operacionais"><a class="icone" href="/admin" title="Voltar ao painel" aria-label="Voltar ao painel">⌂</a><button class="icone botao-som" type="button" data-admin-sound aria-label="Ativar ou desativar sons"><span aria-hidden="true">♫</span></button><?= admin_notifications_menu($orders,$user) ?><?= admin_profile_menu($user) ?></div></header>
<main class="conteudo-operacional"><p class="subtitulo-operacional"><?= e($subtitles[$section]) ?></p><?php if($flash):?><div class="aviso <?= e($flash[0]) ?>"><?= e($flash[1]) ?></div><?php endif;?>
<?php if($section==='waiter'):?><div class="grade-garcom"><article class="cartao painel-mesas-operacional"><h2>MESAS E COMANDAS</h2><?php if(!$activeTables):?><div class="vazio"><strong>Nenhuma mesa cadastrada</strong><p>Cadastre mesas no módulo Salão do painel.</p></div><?php else:?><div class="grade-mesas-operacional"><?php foreach($activeTables as$table):try{$token=decrypt_secret($table['access_token_encrypted']);}catch(Throwable){continue;}$status=$table['status']??'available';?><button type="button" class="mesa-operacional" data-table-token="<?= e($token) ?>"><strong><?= e($table['name']) ?></strong><small><?= e($table['area_name']??'Salão') ?></small><span class="etiqueta estado-mesa-<?= e($status) ?>"><?= e(match($status){'occupied'=>'Ocupada','bill_requested'=>'Conta',default=>'Disponível'}) ?></span></button><?php endforeach;?></div><?php endif;?></article>
<article class="cartao painel-pedido-operacional"><span class="sobretitulo">NOVO PEDIDO DE MESA</span><h2>PEDIDO <span id="selectedTableLabel">· SELECIONE A MESA</span></h2><form id="serviceOrderForm" class="formulario" data-store-slug="<?= e($store['slug']) ?>"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><label>Mesa<select name="table_token" id="serviceTable" required><option value="">Selecione</option><?php foreach($activeTables as$table):try{$token=decrypt_secret($table['access_token_encrypted']);}catch(Throwable){continue;}?><option value="<?= e($token) ?>"><?= e($table['name']) ?> · <?= e($table['area_name']??'Salão') ?></option><?php endforeach;?></select></label><div class="grade duas-colunas"><label>Nome do cliente<input name="customer_name" minlength="2" maxlength="160" required></label><label>Telefone (opcional)<input name="customer_phone" inputmode="tel" maxlength="30"></label></div><label>Pagamento<select name="payment_method"><option value="cash">Acertar no caixa</option><option value="pix">PIX</option><option value="debit">Débito</option><option value="credit">Crédito</option></select></label><fieldset class="lista-produtos-operacional"><legend>PRODUTOS</legend><?php foreach(array_filter($products,fn($p)=>$p['active']) as$p):?><details class="produto-atendimento"><summary><span><b><?= e($p['name']) ?></b><small><?= $money((int)$p['price_cents']) ?></small></span><input class="service-quantity" type="number" data-product-id="<?= (int)$p['id'] ?>" min="0" max="50" value="0" aria-label="Quantidade de <?= e($p['name']) ?>"></summary><?php foreach(array_filter($productOptions,fn($link)=>(int)$link['product_id']===(int)$p['id']) as$link):$group=$groupsById[$link['group_id']]??null;if(!$group||!$group['active'])continue;?><fieldset class="opcoes-atendimento"><legend><?= e($group['name']) ?> · <?= (int)$group['min_choices'] ?>–<?= (int)$group['max_choices'] ?></legend><?php foreach(array_filter($optionItems,fn($item)=>(int)$item['group_id']===(int)$group['id']&&$item['active']) as$option):?><label><input type="<?= $group['selection_type']==='single'?'radio':'checkbox' ?>" name="service_group_<?= (int)$p['id'] ?>_<?= (int)$group['id'] ?>" value="<?= (int)$option['id'] ?>" data-service-option-product="<?= (int)$p['id'] ?>"> <?= e($option['name']) ?><?= $option['price_cents']?' (+'.$money((int)$option['price_cents']).')':'' ?></label><?php endforeach;?></fieldset><?php endforeach;?></details><?php endforeach;?></fieldset><button class="botao primario completo" type="submit">Enviar para cozinha</button><output id="serviceOrderResult" class="aviso" hidden></output></form></article></div>
<?php if($visibleOrders):?><section class="fila-operacional"><div class="titulo-fila"><span class="sobretitulo">OPERAÇÃO EM TEMPO REAL</span><h2>COMANDAS EM ANDAMENTO</h2></div><div class="grade tres-colunas"><?php foreach($visibleOrders as$order):$nextStatus=$next($order['status']);?><article class="cartao pedido-operacional"><div class="cabecalho-cartao"><div><small><?= e($order['public_code']) ?></small><h3><?= e($order['customer_name']) ?></h3></div><span class="etiqueta"><?= e($order['status']) ?></span></div><strong><?= $money((int)$order['total_cents']) ?></strong><?php if($nextStatus):?><form method="post" action="/admin/order/status"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="return_to" value="<?= e($returnPath) ?>"><input type="hidden" name="id" value="<?= (int)$order['id'] ?>"><input type="hidden" name="status" value="<?= e($nextStatus) ?>"><button class="botao primario completo"><?= e($buttonLabels[$nextStatus]) ?></button></form><?php endif;?></article><?php endforeach;?></div></section><?php endif;?>
<?php else:?><section class="fila-operacional"><div class="titulo-fila"><span class="sobretitulo">OPERAÇÃO EM TEMPO REAL</span><h2><?= e($titles[$section]) ?></h2></div><?php if(!$visibleOrders):?><div class="vazio"><strong>Nenhum pedido nesta etapa</strong><p>A fila será atualizada quando novos pedidos chegarem.</p></div><?php else:?><div class="grade tres-colunas grade-kds-operacional"><?php foreach($visibleOrders as$order):$nextStatus=$next($order['status']);?><article class="cartao pedido-operacional estado-pedido-<?= e($order['status']) ?>"><?php $elapsed=max(0,(int)floor((time()-strtotime($order['created_at']))/60)); ?><div class="cabecalho-cartao"><div><small><?= e($order['public_code']) ?> · <?= $elapsed ?> min</small><h3><?= e($order['customer_name']) ?></h3></div><span class="etiqueta"><?= e($statusLabels[$order['status']]??$order['status']) ?></span></div><?php if($section==='courier'):?><p><?= e($order['address']) ?></p><p><?= e($order['customer_phone']) ?> · <?= e($order['payment_method']) ?></p><div class="grupo-botoes"><a class="botao pequeno" href="https://www.google.com/maps/search/?api=1&amp;query=<?= urlencode($order['address']) ?>" target="_blank" rel="noopener noreferrer">Abrir no GPS</a><?php if($order['customer_phone']):?><a class="botao pequeno" href="tel:<?= e(preg_replace('/[^0-9+]/','',$order['customer_phone'])) ?>">Ligar</a><?php endif;?></div><?php endif;?><ul><?php foreach(array_filter($orderItems,fn($i)=>(int)$i['order_id']===(int)$order['id']) as$item):?><li><b><?= (int)$item['quantity'] ?>× <?= e($item['product_name']) ?></b><?php if($item['options_text']):?><small><?= e($item['options_text']) ?></small><?php endif;?><?php if($item['notes']):?><small class="observacao">Obs.: <?= e($item['notes']) ?></small><?php endif;?></li><?php endforeach;?></ul><strong><?= $money((int)$order['total_cents']) ?></strong><?php if($nextStatus):?><form method="post" action="/admin/order/status"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="return_to" value="<?= e($returnPath) ?>"><input type="hidden" name="id" value="<?= (int)$order['id'] ?>"><input type="hidden" name="status" value="<?= e($nextStatus) ?>"><button class="botao primario completo"><?= e($buttonLabels[$nextStatus]) ?></button></form><?php endif;?></article><?php endforeach;?></div><?php endif;?></section><?php endif;?></main><script src="/assets/admin-ui.js?v=20260903-review1" defer></script></body></html>

