<?php
$money=fn(int $value)=>'R$ '.number_format($value/100,2,',','.');
$roleLabels=['platform_admin'=>'Administrador da plataforma','owner'=>'Proprietário','manager'=>'Gerente','attendant'=>'Atendente','waiter'=>'Garçom','kitchen'=>'Cozinha','pos'=>'PDV','courier'=>'Entregador'];
$statusLabels=['received'=>'Recebido','confirmed'=>'Confirmado','preparing'=>'Em preparo','ready'=>'Pronto','out_for_delivery'=>'Em entrega','delivered'=>'Entregue','cancelled'=>'Cancelado','rejected'=>'Recusado'];
$typeLabels=['delivery'=>'Entrega','pickup'=>'Retirada','dine_in'=>'Mesa'];
$columns=['received','confirmed','preparing','ready','out_for_delivery'];
$transitions=['received'=>['confirmed','cancelled','rejected'],'confirmed'=>['preparing','cancelled'],'preparing'=>['ready','cancelled'],'ready'=>['out_for_delivery','delivered','cancelled'],'out_for_delivery'=>['delivered','cancelled']];
$rolePairs=['waiter'=>['received>confirmed'],'kitchen'=>['confirmed>preparing','preparing>ready'],'pos'=>['received>confirmed','confirmed>preparing','preparing>ready','ready>delivered'],'courier'=>['ready>out_for_delivery','out_for_delivery>delivered']];
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pedidos · MJDev Digital</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700;800&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><script src="/assets/admin-theme.js?v=20260826-tema1"></script><link rel="stylesheet" href="/assets/admin.css?v=20260903-review1"></head><body class="secao-orders"><div class="aplicativo"><aside class="barra-lateral" id="sidebar"><div class="marca"><span class="simbolo-marca">MJ</span><div><strong>MJDev Digital</strong><small>PAINEL DE GESTÃO</small></div><button class="icone movel" id="closeMenu" type="button" aria-label="Fechar menu">×</button></div><nav><?= admin_navigation($user['role'],'orders') ?></nav><?= admin_store_card($store) ?><form class="sair-painel" method="post" action="/sair"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><button class="botao perigo">Sair do painel</button></form></aside><div class="fundo-sobreposto fundo-menu" id="menuBackdrop"></div><main class="estrutura"><header class="barra-superior"><button class="icone movel" id="openMenu" type="button" aria-label="Abrir menu">☰</button><div class="cabecalho-pagina"><span><?= e(strtoupper($store['name'])) ?></span><h1>Pedidos</h1></div><?= admin_header_actions($orders,$user) ?></header><section class="conteudo">
<?php if($flash):?><div class="aviso <?= e($flash[0]) ?>"><?= e($flash[1]) ?></div><?php endif;?>
<div class="introducao-modulo"><div><span class="sobretitulo">PEDIDOS › LISTAR</span><h2>Pedidos</h2><p>Gerencie pedidos com visão clara e ações rápidas.</p></div><span class="contador-modulo"><?= count(array_filter($orders,fn($order)=>!in_array($order['status'],['delivered','cancelled','rejected'],true))) ?> ativo(s)</span></div>
<div class="barra-ferramentas ferramentas-pedidos"><label class="busca"><span>⌕</span><input class="busca-local" type="search" placeholder="Pesquisar" aria-label="Pesquisar pedidos"></label><button class="botao" type="button" data-order-filter>☷ Filtros</button><?php if(in_array($user['role'],['platform_admin','owner','manager'],true)):?><form class="exportacao-pedidos" method="get" action="/admin/export/orders"><label>De <input type="date" name="from" value="<?= e(date('Y-m-01')) ?>"></label><label>Até <input type="date" name="to" value="<?= e(date('Y-m-d')) ?>"></label><button class="botao" type="submit">Exportar CSV</button></form><?php endif;?></div>
<article class="cartao cartao-tabela-administrativa"><div class="envoltorio-tabela"><table><thead><tr><th>Código</th><th>Cliente</th><th>Tipo</th><th>Status</th><th>Itens</th><th>Total</th><th>Entregador</th><th>Agendado</th><th>Hora</th><th>Ações</th></tr></thead><tbody><?php if(!$orders):?><tr><td colspan="10"><div class="estado-vazio compacto"><b>Nenhum pedido</b><p>Os novos pedidos aparecerão aqui automaticamente.</p></div></td></tr><?php else:foreach($orders as$order):$status=$order['status'];$allowed=$transitions[$status]??[];if(isset($rolePairs[$user['role']])){$allowed=array_values(array_filter($allowed,fn($next)=>in_array($status.'>'.$next,$rolePairs[$user['role']],true)));}if(($user['role']==='waiter'&&$order['order_type']!=='dine_in')||($user['role']==='pos'&&$order['order_type']!=='pickup')||($user['role']==='courier'&&($order['order_type']!=='delivery'||(int)$order['assigned_courier_id']!==(int)$user['id'])))$allowed=[];$itemCount=array_sum(array_map(fn($item)=>(int)$item['order_id']===(int)$order['id']?(int)$item['quantity']:0,$orderItems));?><tr data-order-terminal="<?= in_array($status,['delivered','cancelled','rejected'],true)?'1':'0' ?>"><td><b><?= e($order['public_code']) ?></b></td><td><b><?= e($order['customer_name']) ?></b><small><?= e($order['customer_phone']) ?></small></td><td><?= e($typeLabels[$order['order_type']]??$order['order_type']) ?></td><td><span class="etiqueta"><?= e($statusLabels[$status]??$status) ?></span></td><td><?= $itemCount ?></td><td><b><?= $money((int)$order['total_cents']) ?></b></td><td><?= e($order['courier_name']??'—') ?></td><td><?= !empty($order['scheduled_for'])?e(date('d/m H:i',strtotime($order['scheduled_for']))):'Não' ?></td><td><?= e(date('H:i',strtotime($order['created_at']))) ?></td><td><?php if($allowed):?><form class="acao-pedido-tabela" method="post" action="/admin/order/status"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$order['id'] ?>"><select name="status"><?php foreach($allowed as$next):?><option value="<?= e($next) ?>"><?= e($statusLabels[$next]) ?></option><?php endforeach;?></select><button class="botao pequeno primario">Atualizar</button></form><?php else:?><span class="suave">—</span><?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></div><footer class="rodape-tabela"><span>Exibindo <?= count($orders) ?> resultado(s)</span><span>Dados reais da loja</span></footer></article>
</section></main></div><script src="/assets/admin-ui.js?v=20260903-review1" defer></script></body></html>

