<?php
$money=fn(int $v)=>'R$ '.number_format($v/100,2,',','.');
$billingLabels=['pending'=>'Não configurada','trialing'=>'Em teste','active'=>'Ativa','past_due'=>'Pagamento pendente','cancelled'=>'Cancelada','expired'=>'Expirada'];
$planLabels=['monthly'=>'Mensal','annual'=>'Anual'];
$today=new DateTimeImmutable('today');
$trialState=static function(array $tenant)use($today):array{
    if(!$tenant['published_at']||!$tenant['trial_ends_at'])return ['Não iniciado',''];
    $end=new DateTimeImmutable($tenant['trial_ends_at']);
    if($end<$today)return ['Encerrado','vermelho'];
    $days=(int)$today->diff($end)->format('%a');
    return [$days===0?'Termina hoje':$days.' dia(s) restante(s)',$days<=3?'amarelo':'verde'];
};
$pageUrl=static function(int $target)use($search,$status):string{return '/platform?'.http_build_query(['q'=>$search,'status'=>$status,'page'=>$target]);};
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administração da plataforma · MJDev Digital</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700;800&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><script src="/assets/admin-theme.js?v=20260826-tema1"></script><link rel="stylesheet" href="/assets/admin.css?v=20260903-review1"></head><body><main class="estrutura plataforma-global"><header class="barra-superior"><div class="cabecalho-pagina"><span>ADMINISTRAÇÃO GLOBAL</span><h1>MJDev Digital</h1></div><a class="botao" href="/admin">Painel da loja vinculada</a><form method="post" action="/sair"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><button class="botao perigo">Sair</button></form></header><section class="conteudo"><?php if($flash):?><div class="aviso <?= e($flash[0]) ?>"><?= e($flash[1]) ?></div><?php endif;?>
<div class="introducao-modulo"><span class="sobretitulo">VISÃO DA PLATAFORMA</span><h2>OPERAÇÃO DO SAAS</h2><p>Acompanhe estabelecimentos, responsáveis, testes e o estado real das assinaturas sem misturar dados entre lojas.</p></div>
<div class="grade metricas metricas-modulo"><article class="metrica"><small>Estabelecimentos</small><strong><?= (int)$stats['tenants'] ?></strong></article><article class="metrica"><small>Lojas ativas</small><strong><?= (int)$stats['active'] ?></strong></article><article class="metrica"><small>Em teste</small><strong><?= (int)$stats['trials'] ?></strong><span><?= (int)$stats['trial_expiring'] ?> encerrando em até 3 dias</span></article><article class="metrica"><small>Assinaturas ativas</small><strong><?= (int)$stats['subscribers'] ?></strong><span><?= (int)$stats['past_due'] ?> com pagamento pendente</span></article><article class="metrica"><small>Usuários ativos</small><strong><?= (int)$stats['users'] ?></strong></article><article class="metrica"><small>Pedidos</small><strong><?= (int)$stats['orders'] ?></strong></article><article class="metrica"><small>Volume das lojas</small><strong><?= $money((int)$stats['revenue']) ?></strong><span>Não representa receita da plataforma</span></article></div>
<form class="barra-ferramentas ferramentas-plataforma" method="get" action="/platform"><label class="busca"><span>⌕</span><input type="search" name="q" maxlength="80" value="<?= e($search) ?>" placeholder="Loja, endereço, cidade ou responsável" aria-label="Pesquisar estabelecimentos"></label><label class="filtro-plataforma"><span>Situação</span><select name="status"><?php foreach(['all'=>'Todas','active'=>'Ativas','suspended'=>'Suspensas','trial_active'=>'Teste ativo','trial_expired'=>'Teste encerrado','subscribed'=>'Assinantes','past_due'=>'Pagamento pendente'] as$value=>$label):?><option value="<?= e($value) ?>" <?= $status===$value?'selected':'' ?>><?= e($label) ?></option><?php endforeach;?></select></label><button class="botao primario">Aplicar filtros</button><?php if($search!==''||$status!=='all'):?><a class="botao" href="/platform">Limpar</a><?php endif;?></form>
<article class="cartao"><div class="cabecalho-cartao"><div><span class="sobretitulo">CLIENTES E LOJAS</span><h2>Estabelecimentos cadastrados</h2></div><span class="etiqueta"><?= (int)$totalTenants ?> encontrado(s)</span></div><?php if(!$tenants):?><div class="estado-vazio"><b>Nenhum estabelecimento encontrado</b><p>Revise o termo pesquisado ou limpe os filtros.</p></div><?php else:?><div class="envoltorio-tabela"><table><thead><tr><th>Estabelecimento</th><th>Responsável</th><th>Teste grátis</th><th>Assinatura</th><th>Operação</th><th>Status</th><th>Controle</th></tr></thead><tbody><?php foreach($tenants as$t):[$trialLabel,$trialClass]=$trialState($t);?><tr><td><a class="link-tabela" href="/platform/tenant?id=<?= (int)$t['id'] ?>"><b><?= e($t['name']) ?></b></a><small><?= e($t['slug']) ?> · <?= e($t['city']) ?> · <?= e($t['business_type']) ?></small></td><td><b><?= e($t['owner_name']??'Não identificado') ?></b><small><?= e($t['owner_email']??'Sem e-mail') ?> · <?= (int)$t['user_count'] ?> usuário(s)</small></td><td><span class="etiqueta <?= e($trialClass) ?>"><?= e($trialLabel) ?></span><?php if($t['trial_ends_at']):?><small>até <?= e((new DateTimeImmutable($t['trial_ends_at']))->format('d/m/Y')) ?></small><?php endif;?></td><td><b><?= e($planLabels[$t['plan_code']]??'Sem plano') ?></b><small><?= e($billingLabels[$t['billing_status']]??'Integração não configurada') ?></small><?php if($t['current_period_end']):?><small>período até <?= e((new DateTimeImmutable($t['current_period_end']))->format('d/m/Y')) ?></small><?php endif;?></td><td><b><?= (int)$t['order_count'] ?> pedido(s)</b><small><?= $money((int)$t['gross_cents']) ?> em vendas</small><small><?= $t['last_order_at']?'Último: '.e((new DateTimeImmutable($t['last_order_at']))->format('d/m/Y H:i')):'Sem pedidos' ?></small></td><td><span class="etiqueta <?= $t['suspended_at']?'vermelho':'verde' ?>"><?= $t['suspended_at']?'Suspensa':'Ativa' ?></span><?php if($t['suspension_reason']):?><small><?= e($t['suspension_reason']) ?></small><?php endif;?></td><td><form method="post" action="/platform/tenant/status"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$t['id'] ?>"><?php if($t['suspended_at']):?><button class="botao pequeno">Reativar</button><?php else:?><input name="reason" minlength="5" maxlength="500" placeholder="Motivo da suspensão" required><button class="botao pequeno perigo" name="suspend" value="1">Suspender</button><?php endif;?></form></td></tr><?php endforeach;?></tbody></table></div><footer class="rodape-tabela paginacao-plataforma"><span>Página <?= (int)$page ?> de <?= (int)$totalPages ?></span><nav aria-label="Paginação de estabelecimentos"><?php if($page>1):?><a class="botao pequeno" href="<?= e($pageUrl($page-1)) ?>">Anterior</a><?php endif;?><?php if($page<$totalPages):?><a class="botao pequeno" href="<?= e($pageUrl($page+1)) ?>">Próxima</a><?php endif;?></nav></footer><?php endif;?></article>
<article class="cartao"><span class="sobretitulo">ASSINATURAS DA PLATAFORMA</span><h2>Integração financeira preparada</h2><p class="suave">O painel já diferencia teste, plano e estado da assinatura. Nenhuma cobrança é simulada: os registros deverão ser atualizados por webhooks autenticados do provedor escolhido.</p></article>
</section></main></body></html>

