<?php
$catalogUrl=rtrim(env('APP_URL','http://localhost'),'/').'/'.$store['slug'];
$published=(bool)$store['published_at'];
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>QR da vitrine · MJDev Digital</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700;800&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><script src="/assets/admin-theme.js?v=20260826-tema1"></script><link rel="stylesheet" href="/assets/admin.css?v=20260903-review1"></head>
<body class="secao-qr"><div class="aplicativo"><aside class="barra-lateral" id="sidebar"><div class="marca"><span class="simbolo-marca">MJ</span><div><strong>MJDev Digital</strong><small>PAINEL DE GESTÃO</small></div><button class="icone movel" id="closeMenu" type="button" aria-label="Fechar menu">×</button></div><nav><?= admin_navigation($user['role'],'qr') ?></nav><?= admin_store_card($store) ?><form class="sair-painel" method="post" action="/sair"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><button class="botao perigo">Sair do painel</button></form></aside><div class="fundo-sobreposto fundo-menu" id="menuBackdrop"></div><main class="estrutura"><header class="barra-superior"><button class="icone movel" id="openMenu" type="button" aria-label="Abrir menu">☰</button><div class="cabecalho-pagina"><span><?= e(strtoupper($store['name'])) ?></span><h1>QR da vitrine</h1></div><?= admin_header_actions($orders,$user) ?></header><section class="conteudo"><div class="introducao-modulo"><span class="sobretitulo">DIVULGUE SUA LOJA</span><h2>QR CODE DO CARDÁPIO DIGITAL</h2><p>Um acesso direto e exclusivo para a vitrine pública de <?= e($store['name']) ?>.</p></div>
<?php if(!$published):?><div class="aviso error">O QR Code já pode ser visualizado, mas os clientes verão a página de preparação até a vitrine ser publicada.</div><?php endif;?>
<div class="grade duas-colunas grade-qr-vitrine"><article class="cartao centro cartao-qr-impressao"><span class="sobretitulo">PRONTO PARA IMPRIMIR</span><h2>Aponte a câmera</h2><div class="qr-code qr-code-grande" data-qr-value="<?= e($catalogUrl) ?>"></div><strong><?= e($store['name']) ?></strong><p class="suave">Escaneie para abrir o cardápio e fazer seu pedido.</p></article><article class="cartao"><span class="sobretitulo">LINK GERADO AUTOMATICAMENTE</span><h2>Compartilhe seu catálogo</h2><p class="suave">O endereço usa o identificador único da empresa e não precisa ser digitado pelo cliente no cadastro.</p><label class="campo-url"><span>Endereço público</span><input value="<?= e($catalogUrl) ?>" readonly></label><div class="grupo-botoes"><button class="botao primario baixar-qr" type="button">Baixar QR Code</button><button class="botao" type="button" onclick="window.print()">Imprimir placa</button><button class="botao" type="button" data-copy-value="<?= e($catalogUrl) ?>">Copiar link</button></div><hr><h3>Onde usar</h3><ul class="lista-beneficios"><li><span>1</span><div><b>Mesas e balcão</b><small>Imprima a placa para acesso rápido ao catálogo público.</small></div></li><li><span>2</span><div><b>Redes sociais</b><small>Compartilhe o mesmo endereço em bio, stories e mensagens.</small></div></li><li><span>3</span><div><b>Materiais impressos</b><small>Use o arquivo SVG em embalagens, cartões e cartazes.</small></div></li></ul><div class="grupo-botoes"><a class="botao" href="https://wa.me/?text=<?= e(rawurlencode('Confira o catálogo da '.$store['name'].': '.$catalogUrl)) ?>" target="_blank" rel="noopener noreferrer">Compartilhar no WhatsApp</a><a class="botao" href="/loja/<?= e($store['slug']) ?>" target="_blank" rel="noopener">Ver vitrine</a></div></article></div></section></main></div><script src="/assets/admin-ui.js?v=20260903-review1" defer></script></body></html>

