<?php
$roleLabels=['owner'=>'Proprietário','manager'=>'Gerente','attendant'=>'Atendente','waiter'=>'Garçom','kitchen'=>'Cozinha','pos'=>'PDV','courier'=>'Entregador','platform_admin'=>'Administrador da plataforma'];
$restaurantOperations=business_type_supports_restaurant_operations((string)($store['business_type']??'Outro'));
$editable=staff_roles_for_business_type((string)($store['business_type']??'Outro'));
$activeMembers=count(array_filter($users,fn($member)=>(bool)$member['active']));
$operationalMembers=count(array_filter($users,fn($member)=>in_array($member['role'],['waiter','kitchen','pos','courier'],true)));
$accessPaths=['waiter'=>'/garcom','kitchen'=>'/cozinha','pos'=>'/pdv','courier'=>'/entregador'];
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Funcionários · MJDev Digital</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700;800&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><script src="/assets/admin-theme.js?v=20260826-tema1"></script><link rel="stylesheet" href="/assets/admin.css?v=20260903-review1"></head><body><div class="aplicativo"><aside class="barra-lateral" id="sidebar"><div class="marca"><span class="simbolo-marca">MJ</span><div><strong>MJDev Digital</strong><small>PAINEL DE GESTÃO</small></div><button class="icone movel" id="closeMenu">×</button></div><nav><?= admin_navigation($user['role'],'users') ?></nav><?= admin_store_card($store) ?><form class="sair-painel" method="post" action="/sair"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><button class="botao perigo">Sair do painel</button></form></aside><div class="fundo-sobreposto fundo-menu" id="menuBackdrop"></div><main class="estrutura"><header class="barra-superior"><button class="icone movel" id="openMenu">☰</button><div class="cabecalho-pagina"><span><?= e(strtoupper($store['name'])) ?></span><h1>Funcionários</h1></div><?= admin_header_actions($orders,$user) ?></header><section class="conteudo"><?php if($flash):?><div class="aviso <?= e($flash[0]) ?>"><?= e($flash[1]) ?></div><?php endif;?>
<div class="introducao-modulo"><div><span class="sobretitulo">RELACIONAMENTO › EQUIPE</span><h2>Funcionários</h2><p>Gerencie acessos individuais e funções da operação.</p></div><button class="botao primario" type="button" data-open-user>+ Criar funcionário</button></div>
<div class="grade quatro-colunas metricas metricas-modulo"><article class="metrica"><small>Total da equipe</small><strong><?= count($users) ?></strong><span>Acessos cadastrados</span></article><article class="metrica"><small>Acessos ativos</small><strong><?= $activeMembers ?></strong><span>Podem entrar no painel</span></article><article class="metrica"><small>Funções operacionais</small><strong><?= $operationalMembers ?></strong><span><?= $restaurantOperations?'Garçom, cozinha, PDV e entrega':'Atendimento, PDV e entrega' ?></span></article><article class="metrica"><small>Inativos</small><strong><?= count($users)-$activeMembers ?></strong><span>Acesso bloqueado</span></article></div>
<div class="barra-ferramentas"><label class="busca"><span>⌕</span><input class="busca-local" type="search" placeholder="Pesquisar funcionário" aria-label="Pesquisar funcionário"></label><span class="resumo-ferramentas">Cada integrante usa seu próprio login.</span><button class="botao primario" type="button" data-open-user>+ Criar funcionário</button></div>
<article class="cartao-tabela-administrativa tabela-equipe"><?php if(!$users):?><div class="estado-vazio"><b>Nenhum integrante cadastrado</b><p>Crie o primeiro acesso da equipe.</p></div><?php else:?><div class="envoltorio-tabela"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Função</th><th>Painel de acesso</th><th>Último acesso</th><th>Situação</th><th>Ações</th></tr></thead><tbody><?php foreach($users as$member):$locked=in_array($member['role'],['owner','platform_admin'],true)||(int)$member['id']===(int)$user['id'];$accessPath=$accessPaths[$member['role']]??'/admin';?><tr><td><strong><?= e($member['name']) ?></strong></td><td><?= e($member['email']) ?></td><td><span class="etiqueta"><?= e($roleLabels[$member['role']]??$member['role']) ?></span></td><td><code><?= e($accessPath) ?></code><small>Login individual obrigatório</small></td><td><?= e($member['last_login_at']??'Nunca') ?></td><td><span class="etiqueta <?= $member['active']?'verde':'vermelho' ?>"><?= $member['active']?'Ativo':'Inativo' ?></span></td><td><?php if($locked):?><span class="etiqueta verde">Acesso protegido</span><?php else:?><div class="acoes"><button class="botao pequeno" type="button" data-show-edit="user-<?= (int)$member['id'] ?>">Editar</button><form method="post" action="/admin/user/status"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$member['id'] ?>"><input type="hidden" name="active" value="<?= $member['active']?'':'1' ?>"><button class="botao pequeno <?= $member['active']?'perigo':'' ?>"><?= $member['active']?'Desativar':'Reativar' ?></button></form></div><?php endif;?></td></tr><?php if(!$locked):?><tr class="detalhe-equipe" id="user-<?= (int)$member['id'] ?>" hidden><td colspan="7"><form class="grade-formulario formulario-equipe" method="post" action="/admin/user/update"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$member['id'] ?>"><label class="campo"><span>Nome</span><input name="name" value="<?= e($member['name']) ?>" maxlength="160" required></label><label class="campo"><span>E-mail</span><input name="email" type="email" value="<?= e($member['email']) ?>" maxlength="190" required></label><label class="campo"><span>Função</span><select name="role"><?php foreach($editable as$role):?><option value="<?= e($role) ?>" <?= $member['role']===$role?'selected':'' ?>><?= e($roleLabels[$role]) ?></option><?php endforeach;?></select></label><button class="botao pequeno primario">Salvar dados</button></form></td></tr><?php endif;?><?php endforeach;?></tbody></table></div><div class="rodape-tabela"><span>Exibindo <?= count($users) ?> integrante(s)</span><span>Cada função entra com e-mail e senha próprios.</span></div><?php endif;?></article>
<dialog id="userDialog" class="modal-administrativo"><div class="cabecalho-modal"><div><span class="sobretitulo">CONTROLE DE ACESSO</span><h2>Novo integrante</h2><p>Cada pessoa recebe seu próprio acesso. A senha é armazenada somente como hash seguro.</p></div><button class="icone" type="button" data-close-user>×</button></div><form class="grade-formulario" method="post" action="/admin/user/create"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><label class="campo"><span>Nome</span><input name="name" maxlength="160" required></label><label class="campo"><span>E-mail</span><input name="email" type="email" maxlength="190" required></label><label class="campo"><span>Função</span><select name="role"><?php foreach($editable as$role):?><option value="<?= e($role) ?>"><?= e($roleLabels[$role]) ?></option><?php endforeach;?></select></label><label class="campo"><span>Senha provisória</span><input name="password" type="password" minlength="15" maxlength="128" autocomplete="new-password" required></label><button class="botao primario completo">Criar acesso</button></form></dialog>
</section></main></div><script src="/assets/admin-ui.js?v=20260903-review1" defer></script></body></html>

