<?php
$states=['received'=>'Recebido','confirmed'=>'Confirmado','preparing'=>'Em preparação','ready'=>'Pronto','out_for_delivery'=>'Saiu para entrega','delivered'=>'Entregue','cancelled'=>'Cancelado','rejected'=>'Recusado'];
$descriptions=['received'=>'Pedido enviado ao estabelecimento.','confirmed'=>'O estabelecimento confirmou o pedido.','preparing'=>'Seu pedido está sendo preparado.','ready'=>$order['order_type']==='delivery'?'Pedido pronto para sair.':'Pedido pronto para retirada.','out_for_delivery'=>'O pedido está a caminho.','delivered'=>'Pedido concluído.'];
$flow=['received','confirmed','preparing','ready'];
if($order['order_type']==='delivery')$flow[]='out_for_delivery';
$flow[]='delivered';
$currentIndex=array_search($order['status'],$flow,true);
$terminal=in_array($order['status'],['cancelled','rejected'],true);
$historyByStatus=[];
foreach($history as$event)$historyByStatus[$event['status']]=$event['created_at'];
$money=fn(int$value):string=>'R$ '.number_format($value/100,2,',','.');
$typeLabels=['delivery'=>'Entrega','pickup'=>'Retirada','dine_in'=>'Pedido na mesa'];
$paymentLabels=['cash'=>'Dinheiro','pix'=>'Pix','debit'=>'Cartão de débito','credit'=>'Cartão de crédito'];
$whatsapp=preg_replace('/\D+/','',(string)($order['tenant_whatsapp']??''));
if($whatsapp&&!str_starts_with($whatsapp,'55'))$whatsapp='55'.$whatsapp;
$trackingUrl=rtrim(env('APP_URL','http://localhost'),'/').'/pedido/'.$token;
$whatsappLines=['Olá! 👋','','Gostaria de confirmar meu pedido '.$order['public_code'].'.','','*PEDIDO*',''];
foreach($items as$item){
    $whatsappLines[]=(int)$item['quantity'].'x '.$item['product_name'].' — '.$money((int)$item['line_total_cents']);
    if(!empty($item['options_text']))$whatsappLines[]='Opções: '.$item['options_text'];
    if(!empty($item['notes']))$whatsappLines[]='Obs.: '.$item['notes'];
    $whatsappLines[]='';
}
$whatsappLines[]='Subtotal: '.$money((int)$order['subtotal_cents']);
if((int)$order['delivery_fee_cents']>0)$whatsappLines[]='Entrega: '.$money((int)$order['delivery_fee_cents']);
if((int)$order['discount_cents']>0)$whatsappLines[]='Desconto: - '.$money((int)$order['discount_cents']);
if((int)$order['service_fee_cents']>0)$whatsappLines[]='Taxa de serviço: '.$money((int)$order['service_fee_cents']);
if((int)$order['convenience_fee_cents']>0)$whatsappLines[]='Taxa de conveniência: '.$money((int)$order['convenience_fee_cents']);
$whatsappLines[]='';
$whatsappLines[]='*TOTAL: '.$money((int)$order['total_cents']).'*';
$whatsappLines[]='';
$whatsappLines[]='Cliente: '.$order['customer_name'];
$whatsappLines[]='Recebimento: '.($typeLabels[$order['order_type']]??$order['order_type']);
if($order['order_type']==='delivery'&&!empty($order['address']))$whatsappLines[]='Endereço: '.$order['address'];
elseif($order['order_type']==='pickup')$whatsappLines[]='Retirada: '.($order['tenant_address']?:'no estabelecimento');
$whatsappLines[]='Pagamento: '.($paymentLabels[$order['payment_method']]??$order['payment_method']);
$whatsappLines[]='';
$whatsappLines[]='Acompanhar pedido:';
$whatsappLines[]=$trackingUrl;
$whatsappMessage=implode("\n",$whatsappLines);
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><?php if(!$terminal&&$order['status']!=='delivered'):?><meta http-equiv="refresh" content="20"><?php endif;?><meta name="robots" content="noindex,nofollow"><title>Pedido <?= e($order['public_code']) ?> · <?= e($order['tenant_name']) ?></title><link rel="stylesheet" href="/assets/app.css?v=20260826-responsivo1"><link rel="stylesheet" href="/assets/loja.css?v=20260904-details1"></head><body class="corpo-acompanhamento">
<a class="atalho-conteudo" href="#conteudo-principal">Pular para o acompanhamento</a><p class="somente-leitor" role="status" aria-live="polite">Status atual: <?= e($states[$order['status']]??$order['status']) ?>. <?= e($descriptions[$order['status']]??'Acompanhe as próximas atualizações.') ?></p>
<header class="cabecalho-acompanhamento"><a href="/loja/<?= e($order['tenant_slug']) ?>"><span class="simbolo-confirmacao">✓</span><span><small>PEDIDO ONLINE</small><strong><?= e($order['tenant_name']) ?></strong></span></a><span class="selo-seguranca">🔒 Link seguro</span></header><span id="conteudo-principal" class="somente-leitor" tabindex="-1">Início do acompanhamento</span>
<?php if(!empty($referralUrl)):?><aside class="convite-indicacao"><div><span class="sobretitulo">INDIQUE E GANHE</span><strong>Compartilhe seu link pessoal</strong><small>Seu benefício será liberado quando o primeiro pedido da pessoa indicada for entregue.</small></div><button class="botao" type="button" data-copy-referral data-referral-url="<?= e($referralUrl) ?>">Copiar link de indicação</button></aside><script src="/assets/tracking.js?v=20260824-referral1" defer></script><?php endif;?>
<main class="pagina-acompanhamento"><section class="confirmacao-pedido"><span class="sobretitulo"><?= $terminal?'ATUALIZAÇÃO DO PEDIDO':($order['status']==='received'?'PEDIDO REALIZADO':'ACOMPANHAMENTO DO PEDIDO') ?></span><h1><?= $terminal?'Precisamos informar você':($order['status']==='received'?'Pedido recebido!':'Seu pedido está conosco') ?></h1><p><?= $terminal?'Consulte o status e fale com o estabelecimento se precisar.':($order['status']==='received'?'Seu pedido já está salvo. Agora você pode enviá-lo manualmente ao estabelecimento pelo WhatsApp e acompanhar tudo por este link.':'Acompanhe cada etapa por esta página. Ela funciona mesmo sem WhatsApp.') ?></p><div class="codigo-pedido"><small>NÚMERO DO PEDIDO</small><strong><?= e($order['public_code']) ?></strong></div></section>
<div class="grade-acompanhamento"><article class="cartao-acompanhamento cartao-status"><div class="topo-acompanhamento"><div><span class="sobretitulo">STATUS ATUAL</span><h2><?= e($states[$order['status']]??$order['status']) ?></h2><p><?= e($descriptions[$order['status']]??'Acompanhe as próximas atualizações.') ?></p></div><strong><?= $money((int)$order['total_cents']) ?></strong></div><?php if($terminal):?><p class="aviso error">Este pedido foi <?= e(mb_strtolower($states[$order['status']])) ?>. Entre em contato com o estabelecimento se precisar de ajuda.</p><?php else:?><div class="linha-tempo-pedido"><?php foreach($flow as$index=>$state):$complete=$currentIndex!==false&&$index<=$currentIndex;$time=$historyByStatus[$state]??null;?><div class="<?= $complete?'concluido':'' ?> <?= $state===$order['status']?'atual':'' ?>"><i><?= $complete?'✓':($index+1) ?></i><span><b><?= e($states[$state]) ?></b><small><?= $time?e(date('d/m · H:i',strtotime($time))):($state===$order['status']?'Etapa atual':'Aguardando') ?></small></span></div><?php endforeach;?></div><?php endif;?><?php if(!empty($earnedRewards)):?><section class="recompensas-pedido"><span class="sobretitulo">BENEFÍCIOS CONQUISTADOS</span><?php foreach($earnedRewards as$reward):?><article><div><b><?= $reward['reward_kind']==='cashback'?'Cashback':'Cupom de fidelidade' ?></b><small><?= $reward['discount_type']==='percent'?(int)$reward['discount_value'].'% de desconto':$money((int)$reward['discount_value']).' de desconto' ?> · válido até <?= e(date('d/m/Y',strtotime($reward['expires_at']))) ?></small></div><code><?= e($reward['code']) ?></code></article><?php endforeach;?><p>Use o código no próximo pedido com o mesmo WhatsApp. Cada benefício pode ser utilizado uma única vez.</p></section><?php endif;?></article>
<aside class="cartao-acompanhamento resumo-acompanhamento"><span class="sobretitulo">RESUMO DO PEDIDO</span><div class="metadados-pedido"><p><span>Recebimento</span><b><?= e($typeLabels[$order['order_type']]??$order['order_type']) ?></b></p><p><span>Pagamento</span><b><?= e($paymentLabels[$order['payment_method']]??$order['payment_method']) ?></b></p><p><span>Realizado em</span><b><?= e(date('d/m/Y H:i',strtotime($order['created_at']))) ?></b></p></div><div class="itens-acompanhamento"><?php foreach($items as$item):?><div><span><b><?= (int)$item['quantity'] ?>× <?= e($item['product_name']) ?></b><?php if($item['options_text']):?><small><?= e($item['options_text']) ?></small><?php endif;?><?php if($item['notes']):?><small>Obs.: <?= e($item['notes']) ?></small><?php endif;?></span><strong><?= $money((int)$item['line_total_cents']) ?></strong></div><?php endforeach;?></div><div class="detalhes-total"><p><span>Subtotal</span><b><?= $money((int)$order['subtotal_cents']) ?></b></p><?php if($order['discount_cents']):?><p><span>Desconto</span><b>− <?= $money((int)$order['discount_cents']) ?></b></p><?php endif;?><?php if($order['delivery_fee_cents']):?><p><span>Entrega</span><b><?= $money((int)$order['delivery_fee_cents']) ?></b></p><?php endif;?><?php if($order['service_fee_cents']):?><p><span>Taxa de serviço</span><b><?= $money((int)$order['service_fee_cents']) ?></b></p><?php endif;?><?php if($order['convenience_fee_cents']):?><p><span>Taxa de conveniência</span><b><?= $money((int)$order['convenience_fee_cents']) ?></b></p><?php endif;?></div><div class="total-acompanhamento"><span>Total confirmado</span><strong><?= $money((int)$order['total_cents']) ?></strong></div></aside></div>
<div class="acoes-acompanhamento"><?php if($order['status']==='delivered'):?><a class="botao primario" href="/avaliar/<?= e($token) ?>">Avaliar produtos do pedido</a><?php endif;?><?php if($whatsapp&&!$terminal&&$order['status']==='received'):?><a class="botao whatsapp-acompanhamento" href="https://wa.me/<?= e($whatsapp) ?>?text=<?= e(rawurlencode($whatsappMessage)) ?>" target="_blank" rel="noopener noreferrer" aria-label="Abrir WhatsApp e enviar pedido">Receber atualizações no WhatsApp</a><?php endif;?><a class="botao" href="<?= e($trackingUrl) ?>">Acompanhar pedido</a><a class="botao" href="/loja/<?= e($order['tenant_slug']) ?>">Voltar ao catálogo</a></div><?php if(!$terminal&&$order['status']!=='delivered'):?><p class="atualizacao-automatica">O pedido permanece salvo mesmo que você não abra ou não envie a mensagem no WhatsApp. Esta página verifica atualizações automaticamente a cada 20 segundos.</p><?php endif;?></main></body></html>
