<?php
$catalogWords=catalog_vocabulary((string)($store['business_type']??'Outro'));
$tracked=count(array_filter($optionItems,static fn(array $item):bool=>$item['stock_quantity']!==null));
$low=count(array_filter($optionItems,static fn(array $item):bool=>$item['stock_quantity']!==null&&(int)$item['stock_quantity']<=5));
?>
<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Estoque por variação · MJDev Digital</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700;800&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><script src="/assets/admin-theme.js?v=20260826-tema1"></script><link rel="stylesheet" href="/assets/admin.css?v=20260903-review1"></head>
<body class="secao-variant-stock"><div class="aplicativo">
<aside class="barra-lateral" id="sidebar"><div class="marca"><span class="simbolo-marca">MJ</span><div><strong>MJDev Digital</strong><small>PAINEL DE GESTÃO</small></div><button class="icone movel" id="closeMenu" type="button" aria-label="Fechar menu">×</button></div><nav><?= admin_navigation($user['role'],$section) ?></nav><?= admin_store_card($store) ?><form class="sair-painel" method="post" action="/sair"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><button class="botao perigo">Sair do painel</button></form></aside>
<div class="fundo-sobreposto fundo-menu" id="menuBackdrop"></div><main class="estrutura"><header class="barra-superior"><button class="icone movel" id="openMenu" type="button" aria-label="Abrir menu">☰</button><div class="cabecalho-pagina"><span>CATÁLOGO · <?= e(strtoupper($store['name'])) ?></span><h1>ESTOQUE POR VARIAÇÃO</h1></div><?= admin_header_actions($orders,$user) ?></header><section class="conteudo">
<?php if($flash):?><div class="aviso <?= e($flash[0]) ?>"><?= e($flash[1]) ?></div><?php endif;?>
<div class="introducao-modulo"><div><span class="sobretitulo">SKU E DISPONIBILIDADE</span><h2><?= e($catalogWords['options']) ?></h2><p>Controle a quantidade de cada tamanho, cor, voltagem, apresentação ou adicional. Deixe o estoque vazio para disponibilidade ilimitada.</p></div><a class="botao" href="/admin?section=options">Configurar variações</a></div>
<div class="grade tres-colunas metricas metricas-modulo"><article class="metrica"><small>Variações cadastradas</small><strong><?= count($optionItems) ?></strong><span>Em todos os grupos</span></article><article class="metrica"><small>Com estoque controlado</small><strong><?= $tracked ?></strong><span>Baixa automática por pedido</span></article><article class="metrica"><small>Estoque baixo</small><strong><?= $low ?></strong><span>Até 5 unidades</span></article></div>
<article class="cartao cartao-tabela-administrativa"><?php if(!$optionItems):?><div class="estado-vazio"><b>Nenhuma variação cadastrada</b><p>Crie grupos e itens antes de controlar o estoque individual.</p><a class="botao primario" href="/admin?section=options">Criar variações</a></div><?php else:?><div class="envoltorio-tabela"><table><thead><tr><th>Grupo</th><th>Variação</th><th>SKU</th><th>Estoque</th><th>Situação</th><th>Ação</th></tr></thead><tbody>
<?php foreach($optionItems as$item):$formId='variant-inventory-'.(int)$item['id'];?><tr><td><?= e($item['group_name']) ?></td><td><strong><?= e($item['name']) ?></strong><form id="<?= e($formId) ?>" method="post" action="/admin/option-inventory/save"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$item['id'] ?>"></form></td><td><input form="<?= e($formId) ?>" name="sku" value="<?= e((string)($item['sku']??'')) ?>" maxlength="80" pattern="[A-Za-z0-9._-]{2,80}" placeholder="SKU opcional"></td><td><input form="<?= e($formId) ?>" name="stock_quantity" type="number" min="0" max="2147483647" value="<?= $item['stock_quantity']===null?'':(int)$item['stock_quantity'] ?>" placeholder="Ilimitado"></td><td><span class="etiqueta <?= !$item['active']?'vermelho':($item['stock_quantity']!==null&&(int)$item['stock_quantity']<=5?'amarelo':'verde') ?>"><?= !$item['active']?'Inativa':($item['stock_quantity']===null?'Ilimitado':((int)$item['stock_quantity'].' un.')) ?></span></td><td><button form="<?= e($formId) ?>" class="botao pequeno">Salvar</button></td></tr><?php endforeach;?>
</tbody></table></div><?php endif;?></article></section></main></div><script src="/assets/admin-ui.js?v=20260903-review1" defer></script></body></html>

